AviaServer/Controllers/DistinationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AviaServer.Database;

namespace AviaServer.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DistinationController : Controller
    {
        private AirportEntities db = new AirportEntities();

        // GET: Distination/DistinationIndex
        public ActionResult DistinationIndex()
        {
            return View(db.Distinations.ToList());
        }

        /*
        // GET: Distination/DistinationDetails/5
        public ActionResult DistinationDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Distination distination = db.Distinations.Find(id);
            if (distination == null)
            {
                return HttpNotFound();
            }
            return View(distination);
        }
        */

        // GET: Distination/DistinationCreate
        public ActionResult DistinationCreate()
        {
            return View();
        }

        // POST: Distination/DistinationCreate
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DistinationCreate([Bind(Include = "Id,Price,Departure,Arrive,Distance,Routes")] Distination distination)
        {
            if (ModelState.IsValid)
            {
                db.Distinations.Add(distination);
                db.SaveChanges();
                DisplaySuccessMessage("Has append a Distination record");
                return RedirectToAction("DistinationIndex");
            }

            DisplayErrorMessage();
            return View(distination);
        }

        // GET: Distination/DistinationEdit/5
        public ActionResult DistinationEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Distination distination = db.Distinations.Find(id);
            if (distination == null)
            {
                return HttpNotFound();
            }
            return View(distination);
        }

        // POST: DistinationDistination/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DistinationEdit([Bind(Include = "Id,Price,Departure,Arrive,Distance,Routes")] Distination distination)
        {
            if (ModelState.IsValid)
            {
                db.Entry(distination).State = EntityState.Modified;
                db.SaveChanges();
                DisplaySuccessMessage("Has update a Distination record");
                return RedirectToAction("DistinationIndex");
            }
            DisplayErrorMessage();
            return View(distination);
        }

        // GET: Distination/DistinationDelete/5
        public ActionResult DistinationDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Distination distination = db.Distinations.Find(id);
            if (distination == null)
            {
                return HttpNotFound();
            }
            return View(distination);
        }

        // POST: Distination/DistinationDelete/5
        [HttpPost, ActionName("DistinationDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult DistinationDeleteConfirmed(int id)
        {
            Distination distination = db.Distinations.Find(id);
            db.Distinations.Remove(distination);
            db.SaveChanges();
            DisplaySuccessMessage("Has delete a Distination record");
            return RedirectToAction("DistinationIndex");
        }

        private void DisplaySuccessMessage(string msgText)
        {
            TempData["SuccessMessage"] = msgText;
        }

        private void DisplayErrorMessage()
        {
            TempData["ErrorMessage"] = "Save changes was unsuccessful.";
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AviaServer/Views/Distination/DistinationCreate.cshtml
@model AviaServer.Database.Distination

@{
    ViewBag.Title = "Create";
}

<h2 class="text-center"><strong>Create Distination</strong></h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("DistinationEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary btn-raised" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "DistinationIndex", null, new { @class = "btn btn-raised btn-success"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AviaServer/Views/Distination/DistinationEdit.cshtml
@model AviaServer.Database.Distination

@{
    ViewBag.Title = "Edit";
}

<h2 class="text-center">Edit Distination</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("DistinationEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-primary btn-raised" value="Save" />
                <input type="button" class="btn btn-danger btn-raised" data-toggle="modal" data-target="#myModal" value="Delete" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "DistinationIndex", null, new { @class = "btn btn-raised btn-success"})
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Warning !!</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item ?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("DistinationDelete", "Distination", new { id=Model.Id}))
                {
                    @Html.AntiForgeryToken()
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-warning">Delete</button>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AviaServer/Views/Distination/DistinationEditForm.cshtml
@model AviaServer.Database.Distination

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Price,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Departure, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Departure, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Departure,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Arrive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Arrive, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Arrive,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Distance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Distance, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Distance,"" , new { @class = "text-danger" })
            </div>
        </div>




AviaServer/Views/Distination/DistinationIndex.cshtml
@model IEnumerable<AviaServer.Database.Distination>

@{
    ViewBag.Title = "Index";
}
<style type='text/css'>
    /*設定 數字靠右*/
    td:nth-child(1){text-align: right;}
    td:nth-child(2){text-align: right;}
    td:nth-child(5){text-align: right;}
</style>
<h1 class="text-center"><strong>Distination</strong></h1>
<p class="text-center">
    @Html.ActionLink("Create New", "DistinationCreate", null, new { @class = "btn btn-danger btn-raised" })
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Departure)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Arrive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Distance)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td style="text-align: left;">
            @Html.ActionLink("Edit", "DistinationEdit", new { id=item.Id }, new { @class = "btn btn-warning btn-raised" })
        </td>
        <td style="text-align: left;">
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td style="text-align: left;">
            @Html.DisplayFor(modelItem => item.Departure)
        </td>
        <td style="text-align: left;">
            @Html.DisplayFor(modelItem => item.Arrive)
        </td>
        <td style="text-align: left;">
            @Html.DisplayFor(modelItem => item.Distance)
        </td>

    </tr>
}

</table>