AviaServer/Controllers/AspNetRoleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AviaServer.Database;

namespace AviaServer.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AspNetRoleController : Controller
    {
        private AirportEntities db = new AirportEntities();

        // GET: AspNetRole/AspNetRoleIndex
        public ActionResult AspNetRoleIndex()
        {
            return View(db.AspNetRoles.ToList());
        }

        /*
        // GET: AspNetRole/AspNetRoleDetails/5
        public ActionResult AspNetRoleDetails(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRole aspNetRole = db.AspNetRoles.Find(id);
            if (aspNetRole == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRole);
        }
        */

        // GET: AspNetRole/AspNetRoleCreate
        public ActionResult AspNetRoleCreate()
        {
            return View();
        }

        // POST: AspNetRole/AspNetRoleCreate
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AspNetRoleCreate([Bind(Include = "Id,Name,AspNetUsers")] AspNetRole aspNetRole)
        {
            if (ModelState.IsValid)
            {
                db.AspNetRoles.Add(aspNetRole);
                db.SaveChanges();
                DisplaySuccessMessage("Has append a AspNetRole record");
                return RedirectToAction("AspNetRoleIndex");
            }

            DisplayErrorMessage();
            return View(aspNetRole);
        }

        // GET: AspNetRole/AspNetRoleEdit/5
        public ActionResult AspNetRoleEdit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRole aspNetRole = db.AspNetRoles.Find(id);
            if (aspNetRole == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRole);
        }

        // POST: AspNetRoleAspNetRole/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AspNetRoleEdit([Bind(Include = "Id,Name,AspNetUsers")] AspNetRole aspNetRole)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetRole).State = EntityState.Modified;
                db.SaveChanges();
                DisplaySuccessMessage("Has update a AspNetRole record");
                return RedirectToAction("AspNetRoleIndex");
            }
            DisplayErrorMessage();
            return View(aspNetRole);
        }

        // GET: AspNetRole/AspNetRoleDelete/5
        public ActionResult AspNetRoleDelete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRole aspNetRole = db.AspNetRoles.Find(id);
            if (aspNetRole == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRole);
        }

        // POST: AspNetRole/AspNetRoleDelete/5
        [HttpPost, ActionName("AspNetRoleDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult AspNetRoleDeleteConfirmed(string id)
        {
            AspNetRole aspNetRole = db.AspNetRoles.Find(id);
            db.AspNetRoles.Remove(aspNetRole);
            db.SaveChanges();
            DisplaySuccessMessage("Has delete a AspNetRole record");
            return RedirectToAction("AspNetRoleIndex");
        }

        private void DisplaySuccessMessage(string msgText)
        {
            TempData["SuccessMessage"] = msgText;
        }

        private void DisplayErrorMessage()
        {
            TempData["ErrorMessage"] = "Save changes was unsuccessful.";
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AviaServer/Controllers/AspNetUserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AviaServer.Database;

namespace AviaServer.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AspNetUserController : Controller
    {
        private AirportEntities db = new AirportEntities();

        // GET: AspNetUser/AspNetUserIndex
        public ActionResult AspNetUserIndex()
        {
            return View(db.AspNetUsers.ToList());
        }

        /*
        // GET: AspNetUser/AspNetUserDetails/5
        public ActionResult AspNetUserDetails(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }
        */

        // GET: AspNetUser/AspNetUserCreate
        public ActionResult AspNetUserCreate()
        {
            return View();
        }

        // POST: AspNetUser/AspNetUserCreate
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AspNetUserCreate([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,AspNetUserClaims,AspNetUserLogins,Purchases,AspNetRoles")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.AspNetUsers.Add(aspNetUser);
                db.SaveChanges();
                DisplaySuccessMessage("Has append a AspNetUser record");
                return RedirectToAction("AspNetUserIndex");
            }

            DisplayErrorMessage();
            return View(aspNetUser);
        }

        // GET: AspNetUser/AspNetUserEdit/5
        public ActionResult AspNetUserEdit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: AspNetUserAspNetUser/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AspNetUserEdit([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,AspNetUserClaims,AspNetUserLogins,Purchases,AspNetRoles")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetUser).State = EntityState.Modified;
                db.SaveChanges();
                DisplaySuccessMessage("Has update a AspNetUser record");
                return RedirectToAction("AspNetUserIndex");
            }
            DisplayErrorMessage();
            return View(aspNetUser);
        }

        // GET: AspNetUser/AspNetUserDelete/5
        public ActionResult AspNetUserDelete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: AspNetUser/AspNetUserDelete/5
        [HttpPost, ActionName("AspNetUserDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult AspNetUserDeleteConfirmed(string id)
        {
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            db.AspNetUsers.Remove(aspNetUser);
            db.SaveChanges();
            DisplaySuccessMessage("Has delete a AspNetUser record");
            return RedirectToAction("AspNetUserIndex");
        }

        private void DisplaySuccessMessage(string msgText)
        {
            TempData["SuccessMessage"] = msgText;
        }

        private void DisplayErrorMessage()
        {
            TempData["ErrorMessage"] = "Save changes was unsuccessful.";
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AviaServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/icon?family=Material+Icons">

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <!-- Bootstrap Material Design -->
    <link rel="stylesheet" href="~/Content/bootstrap-material-design.min.css" />
   
</head>
<body>
    <div class="navbar  navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Airflot system", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Distination", "DistinationIndex", "Distination")</li>
                    <li>@Html.ActionLink("Route", "RouteIndex", "Route")</li>
                    <li>@Html.ActionLink("Purchase", "PurchaseIndex", "Purchase")</li>
                    <li>@Html.ActionLink("Aircraft", "AircraftIndex", "Aircraft")</li>
                    <li>@Html.ActionLink("Users", "AspNetUserIndex", "AspNetUser")</li>
                    <li>@Html.ActionLink("UserRoles", "AspNetRoleIndex", "AspNetRole")</li>
                </ul>
                   
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
       
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc2/angular-material.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>