AviaServer/Controllers/AircraftController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AviaServer.Database;

namespace AviaServer.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AircraftController : Controller
    {
        private AirportEntities db = new AirportEntities();

        // GET: Aircraft/AircraftIndex
        public ActionResult AircraftIndex()
        {
            return View(db.Aircraft.ToList());
        }

        /*
        // GET: Aircraft/AircraftDetails/5
        public ActionResult AircraftDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aircraft aircraft = db.Aircraft.Find(id);
            if (aircraft == null)
            {
                return HttpNotFound();
            }
            return View(aircraft);
        }
        */

        // GET: Aircraft/AircraftCreate
        public ActionResult AircraftCreate()
        {
            return View();
        }

        // POST: Aircraft/AircraftCreate
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AircraftCreate([Bind(Include = "Id,GovId,Capacity,Title,Description,Routes")] Aircraft aircraft)
        {
            if (ModelState.IsValid)
            {
                db.Aircraft.Add(aircraft);
                db.SaveChanges();
                DisplaySuccessMessage("Has append a Aircraft record");
                return RedirectToAction("AircraftIndex");
            }

            DisplayErrorMessage();
            return View(aircraft);
        }

        // GET: Aircraft/AircraftEdit/5
        public ActionResult AircraftEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aircraft aircraft = db.Aircraft.Find(id);
            if (aircraft == null)
            {
                return HttpNotFound();
            }
            return View(aircraft);
        }

        // POST: AircraftAircraft/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AircraftEdit([Bind(Include = "Id,GovId,Capacity,Title,Description,Routes")] Aircraft aircraft)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aircraft).State = EntityState.Modified;
                db.SaveChanges();
                DisplaySuccessMessage("Has update a Aircraft record");
                return RedirectToAction("AircraftIndex");
            }
            DisplayErrorMessage();
            return View(aircraft);
        }

        // GET: Aircraft/AircraftDelete/5
        public ActionResult AircraftDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aircraft aircraft = db.Aircraft.Find(id);
            if (aircraft == null)
            {
                return HttpNotFound();
            }
            return View(aircraft);
        }

        // POST: Aircraft/AircraftDelete/5
        [HttpPost, ActionName("AircraftDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult AircraftDeleteConfirmed(int id)
        {
            Aircraft aircraft = db.Aircraft.Find(id);
            db.Aircraft.Remove(aircraft);
            db.SaveChanges();
            DisplaySuccessMessage("Has delete a Aircraft record");
            return RedirectToAction("AircraftIndex");
        }

        private void DisplaySuccessMessage(string msgText)
        {
            TempData["SuccessMessage"] = msgText;
        }

        private void DisplayErrorMessage()
        {
            TempData["ErrorMessage"] = "Save changes was unsuccessful.";
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AviaServer/Views/Aircraft/AircraftCreate.cshtml
@model AviaServer.Database.Aircraft

@{
    ViewBag.Title = "Create";
}

<h2 class="text-center"><strong>Create Aircraft</strong></h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("AircraftEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary btn-raised" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "AircraftIndex", null, new { @class = "btn btn-raised btn-success"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AviaServer/Views/Aircraft/AircraftEdit.cshtml
@model AviaServer.Database.Aircraft

@{
    ViewBag.Title = "Edit";
}

<h2 class="text-center">Edit Aircraft</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("AircraftEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-primary btn-raised" value="Save" /> 
                <input type="button" class="btn btn-danger btn-raised" data-toggle="modal" data-target="#myModal" value="Delete" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "AircraftIndex",null,new {@class="btn btn-raised btn-success"})
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="left: 0 !important;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Warning !!</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item ?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("AircraftDelete", "Aircraft", new { id=Model.Id}))
                {
                    @Html.AntiForgeryToken()
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-warning">Delete</button>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AviaServer/Views/Aircraft/AircraftEditForm.cshtml
@model AviaServer.Database.Aircraft

        <div class="form-group">
            @Html.LabelFor(model => model.GovId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GovId, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.GovId,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Capacity,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Title,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Description,"" , new { @class = "text-danger" })
            </div>
        </div>




AviaServer/Views/Aircraft/AircraftIndex.cshtml
@model IEnumerable<AviaServer.Database.Aircraft>

@{
    ViewBag.Title = "Index";
}
<style type='text/css'>
    /*設定 數字靠右*/
    td:nth-child(1){text-align: right;}
    td:nth-child(3){text-align: right;}
</style>
<h1 class="text-center"><strong>Aircraft</strong></h1>
<p class="text-center">
    @Html.ActionLink("Create New", "AircraftCreate",null,new {@class= "btn-raised btn btn-danger" })
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.GovId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Capacity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td style="text-align: left;">
            @Html.ActionLink("Edit", "AircraftEdit", new { id=item.Id },new {@class="btn btn-warning btn-raised"})
        </td>
        <td style="text-align: left;">
            @Html.DisplayFor(modelItem => item.GovId)
        </td>
        <td style="text-align: left;">
            @Html.DisplayFor(modelItem => item.Capacity)
        </td>
        <td style="text-align: left;">
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td style="text-align: left;">
            @Html.DisplayFor(modelItem => item.Description)
        </td>

    </tr>
}

</table>