AviaServer/Controllers/RouteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AviaServer.Database;

namespace AviaServer.Controllers
{
    public static class MCVExtentions
    {
        public static List<SelectListItem> ToSelectList<T>(
            this IEnumerable<T> enumerable,
            Func<T, string> text,
            Func<T, string> value,
            string defaultOption)
        {
            var items = enumerable.Select(f => new SelectListItem()
            {
                Text = text(f),
                Value = value(f)
            }).ToList();
            items.Insert(0, new SelectListItem()
            {
                Text = defaultOption,
                Value = "-1"
            });
            return items;
        }
    }
    [Authorize(Roles = "Admin")]
    public class RouteController : Controller
    {
        private AirportEntities db = new AirportEntities();

        // GET: Route/RouteIndex
        public ActionResult RouteIndex()
        {
            var route = db.Routes.Include(r => r.Aircraft).Include(r => r.Distination);
            return View(route.ToList());
        }

        /*
        // GET: Route/RouteDetails/5
        public ActionResult RouteDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = db.Routes.Find(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            return View(route);
        }
        */

        // GET: Route/RouteCreate
        public ActionResult RouteCreate()
        {
            ViewBag.DestinationId = db.Distinations.ToSelectList(p => p.Departure + "-" + p.Arrive, p => p.Id.ToString(),
          "-");
            ViewBag.AircraftId = new SelectList(db.Aircraft, "Id", "GovId");
            //ViewBag.DestinationId = new SelectList(db.Distinations, "Id", "Departure");
            return View();
        }

        // POST: Route/RouteCreate
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RouteCreate([Bind(Include = "Id,AircraftId,DestinationId,DateStart,DateEnd,Aircraft,Distination,Purchases")] Route route)
        {
            if (ModelState.IsValid)
            {
                db.Routes.Add(route);
                db.SaveChanges();
                DisplaySuccessMessage("Has append a Route record");
                return RedirectToAction("RouteIndex");
            }

            ViewBag.AircraftId = new SelectList(db.Aircraft, "Id", "GovId", route.AircraftId);
            ViewBag.DestinationId = db.Distinations.ToSelectList(p => p.Departure + "-" + p.Arrive, p => p.Id.ToString(),
           "-");
            DisplayErrorMessage();
            return View(route);
        }

        // GET: Route/RouteEdit/5
        public ActionResult RouteEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = db.Routes.Find(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            ViewBag.AircraftId = new SelectList(db.Aircraft, "Id", "GovId", route.AircraftId);
            ViewBag.DestinationId = db.Distinations.ToSelectList(p => p.Departure + "-" + p.Arrive, p => p.Id.ToString(),
           "-");
            return View(route);
        }

        // POST: RouteRoute/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RouteEdit([Bind(Include = "Id,AircraftId,DestinationId,DateStart,DateEnd,Aircraft,Distination,Purchases")] Route route)
        {
            if (ModelState.IsValid)
            {
                db.Entry(route).State = EntityState.Modified;
                db.SaveChanges();
                DisplaySuccessMessage("Has update a Route record");
                return RedirectToAction("RouteIndex");
            }
            ViewBag.AircraftId = new SelectList(db.Aircraft, "Id", "GovId", route.AircraftId);
            ViewBag.DestinationId = db.Distinations.ToSelectList(p => p.Departure + "-" + p.Arrive, p => p.Id.ToString(),
           "-");
            DisplayErrorMessage();
            return View(route);
        }

        // GET: Route/RouteDelete/5
        public ActionResult RouteDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = db.Routes.Find(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            return View(route);
        }

        // POST: Route/RouteDelete/5
        [HttpPost, ActionName("RouteDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult RouteDeleteConfirmed(int id)
        {
            Route route = db.Routes.Find(id);
            db.Routes.Remove(route);
            db.SaveChanges();
            DisplaySuccessMessage("Has delete a Route record");
            return RedirectToAction("RouteIndex");
        }

        private void DisplaySuccessMessage(string msgText)
        {
            TempData["SuccessMessage"] = msgText;
        }

        private void DisplayErrorMessage()
        {
            TempData["ErrorMessage"] = "Save changes was unsuccessful.";
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AviaServer/Views/Route/RouteCreate.cshtml
@model AviaServer.Database.Route

@{
    ViewBag.Title = "Create";
}

<h2 class="text-center"><strong>Create Route</strong></h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("RouteEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary btn-raised" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "RouteIndex", null, new { @class = "btn btn-raised btn-success"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AviaServer/Views/Route/RouteEdit.cshtml
@model AviaServer.Database.Route

@{
    ViewBag.Title = "Edit";
}

<h2 class="text-center">Edit Route</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("RouteEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-primary btn-raised" value="Save" />
                <input type="button" class="btn btn-danger btn-raised" data-toggle="modal" data-target="#myModal" value="Delete" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "RouteIndex", null, new { @class = "btn btn-raised btn-success"})
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Warning !!</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item ?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("RouteDelete", "Route", new { id=Model.Id}))
                {
                    @Html.AntiForgeryToken()
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-warning">Delete</button>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AviaServer/Views/Route/RouteEditForm.cshtml
@model AviaServer.Database.Route

        <div class="form-group">
            @Html.LabelFor(model => model.AircraftId, "AircraftId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AircraftId", null, htmlAttributes: new { @class = "form-control", @required = "required" })
                @Html.ValidationMessageFor(model => model.AircraftId,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DestinationId, "DestinationId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DestinationId", null, htmlAttributes: new { @class = "form-control",@required="required" })
                @Html.ValidationMessageFor(model => model.DestinationId,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateStart, "Date")
                @Html.ValidationMessageFor(model => model.DateStart,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateEnd, "Date")
                @Html.ValidationMessageFor(model => model.DateEnd,"" , new { @class = "text-danger" })
            </div>
        </div>




AviaServer/Views/Route/RouteIndex.cshtml
@model IEnumerable<AviaServer.Database.Route>

@{
    ViewBag.Title = "Index";
}
<style type='text/css'>
    /*設定 數字靠右*/
    td:nth-child(1){text-align: right;}
    td:nth-child(2){text-align: right;}
    td:nth-child(3){text-align: right;}
</style>
<h1 class="text-center"><strong>Route</strong></h1>
<p class="text-center">
    @Html.ActionLink("Create New", "RouteCreate", null, new { @class = "btn btn-danger btn-raised" })
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.DateStart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateEnd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Aircraft.GovId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Distination.Departure)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td style="text-align: left;">
            @Html.ActionLink("Edit", "RouteEdit", new { id=item.Id }, new { @class = "btn btn-warning btn-raised" })
        </td>
        <td style="text-align: left;">
            @Html.DisplayFor(modelItem => item.DateStart)
        </td>
        <td style="text-align: left;">
            @Html.DisplayFor(modelItem => item.DateEnd)
        </td>
        <td style="text-align: left;">
            @Html.DisplayFor(modelItem => item.Aircraft.GovId)
        </td>
        <td style="text-align: left;">
            @Html.DisplayFor(modelItem => item.Distination.Departure)
        </td>

    </tr>
}

</table>